# Generated by Django 6.1 on 2026-09-02 12:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=300, verbose_name='প্রোডাক্টের নাম')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='প্রোডাক্টের ছবি')),
                ('Product_Description', models.CharField(max_length=500, verbose_name='প্রোডাক্টের বিবরণ')),
                ('Key_Features', models.CharField(max_length=500, verbose_name='মূল বৈশিষ্ট্যসমূহ')),
                ('Why_Choose_This_Product', models.CharField(max_length=500, verbose_name='কেন এই প্রোডাক্টটি বেছে নেবেন')),
                ('Suitable_For', models.CharField(max_length=500, verbose_name='কার জন্য উপযোগী')),
                ('Refund_Exchange_Policy', models.CharField(max_length=500, verbose_name='রিফান্ড ও এক্সচেঞ্জ পলিসি')),
                ('total_product', models.PositiveIntegerField(default=0, verbose_name='মোট পণ্যের পরিমাণ (স্টক)')),
            ],
        ),
        migrations.CreateModel(
            name='product_size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productsize', models.CharField(blank=True, max_length=500, null=True, verbose_name='প্রোডাক্ট সাইজ')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='দাম')),
                ('weight', models.PositiveIntegerField(verbose_name='ওজন')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sizes', to='products.products', verbose_name='প্রোডাক্ট')),
            ],
        ),
    ]
