# Generated by Django 6.1 on 2026-09-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('bubble_wrap', 'বাবল র\u200d্যাপ'), ('tape', 'টেপ'), ('box', 'বক্স'), ('pen', 'পেন'), ('tape_cutter', 'টেপ কাটার')], default='bubble_wrap', max_length=50, verbose_name='ক্যাটাগরি'),
            preserve_default=False,
        ),
    ]
